name: Assign Random Reviewer

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign a random reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewers = ['nlopezbelsue', 'SantiagoDopazo', 'axcaputo'];
            const randomReviewer = reviewers[Math.floor(Math.random() * reviewers.length)];
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [randomReviewer]
            });